# Generated by Django 4.2.8 on 2025-06-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('SUV', 'SUV'), ('SEDAN', 'Sedan'), ('TRUCK', 'Truck'), ('HATCHBACK', 'Hatchback'), ('VAN', 'Van'), ('SPORTS', 'Sports Car'), ('LUXURY', 'Luxury Vehicle'), ('ELECTRIC', 'Electric Vehicle'), ('HYBRID', 'Hybrid Vehicle')], max_length=15),
        ),
    ]
